# This workflow performs basic steps
# build, compile, synth and unit test
name: AWS Infra Build

on:
  push:
  pull_request:
  create:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  print_context:
    name: print context values
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo github context json values = $GITHUB_CONTEXT_JSON
          echo vars context json = $VARS_JSON
        env:
          GITHUB_CONTEXT_JSON: ${{ toJSON(github) }}
          VARS_JSON: ${{ toJSON(vars) }}

  build:
    name: npm Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm ci
      - run: npm run build

  unittest:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm ci
      - run: npm run test

  synth_prod:
    name: Synthesize Stacks
    runs-on: ubuntu-latest
    needs:
      - build
    environment: aws-infra-prod
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: mkdir -p dist/lambda_layer/nodejs
      - run: mkdir -p dist/ui
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "synth"
          actions_comment: false
        env:
          INFRA_ENV: ${{ vars.INFRA_ENV }}

  synth:
    name: Synthesize Stacks
    runs-on: ubuntu-latest
    needs:
      - build
    environment: aws-infra-test
    if: github.ref != 'refs/heads/master' && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: mkdir -p dist/lambda_layer/nodejs
      - run: mkdir -p dist/ui
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "synth"
          actions_comment: false
        env:
          INFRA_ENV: ${{ vars.INFRA_ENV }}
