name: UI Deploy to AWS

on:
  repository_dispatch:
    types:
      - on-demand-deploy-ui

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  print_client_payload:
    name: Print client payload of dispatch event
    runs-on: ubuntu-latest
    steps:
      - name: print artifact details
        run: |
          artifact_url=${{ github.event.client_payload.artifact_url }}
          echo "Artifact Url: $artifact_url"
          artifact_name=${{ github.event.client_payload.artifact_name }}
          echo "Artifact Name: $artifact_name"
          ui_repo_run_id=${{ github.event.client_payload.repo_run_id }}
          echo "UI Repository Run Id: $ui_repo_run_id where artifact can be found"
          ui_repository=${{ github.event.client_payload.ui_repository }}
          echo "UI Repository: $ui_repository"
      - name: print github context
        run: echo github context json values = $GITHUB_CONTEXT_JSON
        # env:
        # GITHUB_CONTEXT_JSON: ${{ toJSON(github) }}

  verify_artifact:
    name: Download and Verify UI Artifact
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p dist/ui
      - name: download UI artifact
        uses: actions/download-artifact@v4
        with:
          path: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.ui_repository }}
          run-id: ${{ github.event.client_payload.repo_run_id }}
      - run: ls -lrt dist/${{ github.event.client_payload.artifact_name }}
      - name: Copy artifact files to UI asset directory
        run: cp -r dist/$ARTIFACT_NAME/* dist/ui
        env:
          ARTIFACT_NAME: ${{ github.event.client_payload.artifact_name }}
      - name: validate UI asset directory structure
        run: |
          ls -lrt dist/ui
          ls dist/ui/index.html
          ls -lrt dist/ui/static
          ls dist/ui/logo.jpeg
          ls dist/ui/logo192.png
          ls -lrt dist/ui/static/css
          ls -lrt dist/ui/static/js
          ls -lrt dist/ui/static/media
          ls -lrt dist/ui/favicon.ico

  awsauth:
    name: Verify AWS Access
    runs-on: ubuntu-latest
    environment: aws-infra-master
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          # setup cicd role through instructions from aws-manual branch.
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: cdkSession

  diff:
    name: UI stack diff
    runs-on: ubuntu-latest
    needs:
      - awsauth
    environment: aws-infra-master
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: mkdir -p dist/lambda_layer/nodejs
      - run: mkdir -p dist/ui
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          # setup cicd role through instructions from aws-manual branch.
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: cdkSession
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "diff"
          actions_comment: false
          cdk_args: "MyFinanceUiDeployStack"
        env:
          INFRA_ENV: ${{ vars.INFRA_ENV }}

  deployment:
    name: deploy UI stack
    runs-on: ubuntu-latest
    needs:
      - print_client_payload
      - awsauth
      - diff
      - verify_artifact
    environment: aws-infra-master
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm --version
      - run: npm ci
      - run: npm run build
      - run: mkdir -p dist/lambda_layer/nodejs
      - run: mkdir -p dist/ui
      - name: download UI artifact
        uses: actions/download-artifact@v4
        with:
          path: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.ui_repository }}
          run-id: ${{ github.event.client_payload.repo_run_id }}
      - run: ls -lrt dist/${{ github.event.client_payload.artifact_name }}
      - name: Copy artifact files to UI asset directory
        run: cp -r dist/$ARTIFACT_NAME/* dist/ui
        env:
          ARTIFACT_NAME: ${{ github.event.client_payload.artifact_name }}
      - name: validate UI asset directory structure
        run: |
          ls -lrt dist/ui
          ls dist/ui/index.html
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          # setup cicd role through instructions from aws-manual branch.
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: cdkSession
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          actions_comment: false
          debug_log: true
          cdk_stack: "MyFinanceUiDeployStack"
          cdk_args: "--require-approval never --exclusively"
        env:
          INFRA_ENV: ${{ vars.INFRA_ENV }}

  invalidate_cache:
    name: Invalidate cf cache
    runs-on: ubuntu-latest
    needs:
      - deployment
    environment: aws-infra-master
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          # setup cicd role through instructions from aws-manual branch.
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: cdkSession
      - run: |
          echo aws cloudformation describe-stacks --stack-name prsfin-$INFRA_ENV-infra-stack --query 'Stacks[0].Outputs[?starts_with(OutputKey,`DistributionId`) == `true`].OutputValue' --output text
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name prsfin-$INFRA_ENV-infra-stack --query "Stacks[0].Outputs[?starts_with(OutputKey,`DistributionId`) == `true`].OutputValue' --output text)
          echo Distribution Id = $DISTRIBUTION_ID
          echo aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/personal-finance/index.html" --query "Invalidation.Id" --output text
          INVALIDATION_ID=`aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/personal-finance/index.html" --query "Invalidation.Id" --output text`
          echo Invalidation Id = $INVALIDATION_ID
          INVALIDATION_STATUS="inprogress"
          until [ "$INVALIDATION_STATUS" == "Completed" ]; do
            echo aws cloudfront get-invalidation --id $INVALIDATION_ID --distribution-id $DISTRIBUTION_ID --query "Invalidation.Status" --output text
            INVALIDATION_STATUS=`aws cloudfront get-invalidation --id $INVALIDATION_ID --distribution-id $DISTRIBUTION_ID --query "Invalidation.Status" --output text`
            echo invalidation status = $INVALIDATION_STATUS
            sleep 15
          done
          echo The task, to invalidate cache for index.html, is now completed.
        env:
          INFRA_ENV: ${{ vars.INFRA_ENV }}
    