name: Invalidate cf temp

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  invalidate_cache:
    name: Invalidate cf cache
    runs-on: ubuntu-latest
    environment: aws-infra-master
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          # setup cicd role through instructions from aws-manual branch.
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: cdkSession
      - run: |
          echo aws cloudformation describe-stacks --stack-name prsfin-$INFRA_ENV-infra-stack --query 'Stacks[0].Outputs[?starts_with(OutputKey,`DistributionId`) == `true`].OutputValue' --output text
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name prsfin-$INFRA_ENV-infra-stack --query 'Stacks[0].Outputs[?starts_with(OutputKey,`DistributionId`) == `true`].OutputValue' --output text)
          echo Distribution Id = $DISTRIBUTION_ID
          echo aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/personal-finance/index.html" --query "Invalidation.Id" --output text
          INVALIDATION_ID=`aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/personal-finance/index.html" --query "Invalidation.Id" --output text`
          echo Invalidation Id = $INVALIDATION_ID
          INVALIDATION_STATUS="inprogress"
          until [ "$INVALIDATION_STATUS" == "Completed" ]; do
            echo aws cloudfront get-invalidation --id $INVALIDATION_ID --distribution-id $DISTRIBUTION_ID --query "Invalidation.Status" --output text
            INVALIDATION_STATUS=`aws cloudfront get-invalidation --id $INVALIDATION_ID --distribution-id $DISTRIBUTION_ID --query "Invalidation.Status" --output text`
            echo invalidation status = $INVALIDATION_STATUS
            sleep 15
          done
          echo The task, to invalidate cache for index.html, is now completed.
        env:
          INFRA_ENV: ${{ vars.INFRA_ENV }}
    